// Engine tests: real files generated by FFmpeg, results checked by FFmpeg itself.
// Run: node --test tests/   (requires ffmpeg + ffprobe on PATH)
import { test, before } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, openAsBlob, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const MetaFix = require("../js/mp4.js");

const dir = mkdtempSync(join(tmpdir(), "3dmetafix-"));
process.on("exit", () => rmSync(dir, { recursive: true, force: true }));

const ff = (...args) => execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", ...args]);
const src = ["-f", "lavfi", "-i", "testsrc2=size=512x256:rate=30:duration=2", "-f", "lavfi", "-i", "sine=frequency=440:duration=2"];
const h264 = ["-c:v", "libx264", "-preset", "ultrafast", "-g", "15", "-c:a", "aac", "-shortest"];

const FIXTURES = {
  "faststart.mp4": [...src, ...h264, "-movflags", "+faststart"],
  "moovend.mp4": [...src, ...h264],
  "clip.mov": [...src, ...h264, "-f", "mov"],
  "faststart.mov": [...src, ...h264, "-f", "mov", "-movflags", "+faststart"],
  "frag.mp4": [...src, ...h264, "-movflags", "frag_keyframe+empty_moov"],
  "frag_dbm.mp4": [...src, ...h264, "-movflags", "frag_keyframe+empty_moov+default_base_moof"],
  "reserved.mp4": [...src, ...h264, "-moov_size", "20000"],
  "hevc.mp4": [...src, "-c:v", "libx265", "-preset", "ultrafast", "-x265-params", "log-level=error", "-tag:v", "hvc1", "-c:a", "aac", "-shortest", "-movflags", "+faststart"],
  "twovideo.mp4": [...src, "-map", "0:v", "-map", "0:v", "-map", "1:a", ...h264, "-movflags", "+faststart"]
};

const path = (n) => join(dir, n);
const blobOf = async (n) => openAsBlob(path(n));

before(() => {
  for (const [name, args] of Object.entries(FIXTURES)) ff(...args, path(name));
});

function probe(file) {
  const out = execFileSync("ffprobe", ["-v", "error", "-show_streams", "-select_streams", "v", "-of", "json", file]);
  return JSON.parse(out).streams;
}
function sideData(file) {
  const s = probe(file)[0];
  const list = s.side_data_list || [];
  return {
    spherical: list.find((d) => d.side_data_type === "Spherical Mapping") || null,
    stereo: list.find((d) => d.side_data_type === "Stereo 3D") || null
  };
}
/** Hash of every demuxed packet in every stream — identical ⇔ media untouched. */
function packetHashes(file) {
  const out = execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-i", file, "-map", "0", "-c", "copy", "-f", "framemd5", "-"]).toString();
  return out.split("\n").filter((l) => l && !l.startsWith("#")).join("\n");
}

async function writeFormat(inName, outName, options) {
  const inBlob = await blobOf(inName);
  const a = await MetaFix.analyze(inBlob, { name: inName });
  const spec = MetaFix.buildSpec(options);
  const p = MetaFix.plan(a, spec);
  const outBlob = MetaFix.buildBlob(inBlob, p);
  writeFileSync(path(outName), new Uint8Array(await outBlob.arrayBuffer()));
  const v = await MetaFix.verify(inBlob, await blobOf(outName), a, p);
  return { a, p, v };
}

test("analyze: reports structure for every fixture", async () => {
  for (const name of Object.keys(FIXTURES)) {
    const a = await MetaFix.analyze(await blobOf(name), { name });
    assert.equal(a.video.width, 512, name);
    assert.equal(a.video.height, 256, name);
    assert.equal(a.meta.effective, null, `${name} should have no spherical metadata`);
    assert.equal(a.writable, true, name);
    assert.equal(a.container, name.endsWith(".mov") ? "mov" : "mp4", name);
  }
  const fs = await MetaFix.analyze(await blobOf("faststart.mp4"));
  assert.equal(fs.faststart, true);
  assert.equal(fs.video.codecName, "H.264");
  assert.ok(Math.abs(fs.duration - 2) < 0.1);
  const fr = await MetaFix.analyze(await blobOf("frag.mp4"));
  assert.equal(fr.fragmented, true);
  assert.equal((await MetaFix.analyze(await blobOf("hevc.mp4"))).video.codecName, "HEVC");
});

const CASES = [
  { format: "180-sbs", projection: "tiled equirectangular", stereo: "side by side" },
  { format: "360-mono", projection: "equirectangular", stereo: null },
  { format: "360-tb", projection: "equirectangular", stereo: "top and bottom" },
  { format: "180-mono", projection: "tiled equirectangular", stereo: null },
  { format: "flat-sbs", projection: null, stereo: "side by side" }
];

for (const name of Object.keys(FIXTURES)) {
  test(`inject into ${name}: ffprobe reads it, media untouched, self-verify passes`, async () => {
    const original = packetHashes(path(name));
    for (const c of CASES) {
      const out = `${c.format}_${name}`;
      const { p, v, a } = await writeFormat(name, out, { format: c.format });
      const sd = sideData(path(out));
      if (c.projection) {
        assert.ok(sd.spherical, `${out}: spherical side data missing`);
        assert.equal(sd.spherical.projection, c.projection, out);
        if (c.format.startsWith("180")) {
          // ffprobe prints tile bounds in pixels of the full frame: a 180° crop pads by exactly one frame width.
          assert.equal(sd.spherical.bound_left + sd.spherical.bound_right, 512, `${out}: VR180 bounds`);
          assert.ok(Math.abs(sd.spherical.bound_left - sd.spherical.bound_right) <= 2, `${out}: VR180 bounds centred`);
        }
      } else {
        assert.equal(sd.spherical, null, `${out}: unexpected spherical`);
      }
      assert.equal(sd.stereo ? sd.stereo.type : null, c.stereo, `${out}: stereo`);
      assert.equal(packetHashes(path(out)), original, `${out}: media packets changed`);
      assert.ok(v.ok, `${out}: verify failed ${JSON.stringify(v.checks)}`);
      assert.equal(v.after.meta.effective.key, c.format, `${out}: reads back as ${c.format}`);
      assert.equal(p.videoTracks, a.tracks.filter((t) => t.handler === "vide").length);
    }
  });
}

test("strategy: moov-at-end needs no remap, faststart remaps, reserved space absorbs", async () => {
  assert.equal((await writeFormat("moovend.mp4", "s1.mp4", { format: "180-sbs" })).p.strategy, "tail");
  const fs = (await writeFormat("faststart.mp4", "s2.mp4", { format: "180-sbs" })).p;
  assert.equal(fs.strategy, "remap");
  assert.ok(fs.remapped > 0);
  const rs = (await writeFormat("reserved.mp4", "s3.mp4", { format: "180-sbs" })).p;
  assert.equal(rs.strategy, "padding", "free space reserved by -moov_size should absorb the new header");
  assert.equal(rs.outputSize, (await blobOf("reserved.mp4")).size, "file size unchanged");
  const fr = (await writeFormat("frag.mp4", "s4.mp4", { format: "360-mono" })).p;
  assert.equal(fr.strategy, "remap", "explicit tfhd base offsets / tfra must be remapped");
});

test("re-inject and remove are clean and keep the header stable", async () => {
  await writeFormat("faststart.mp4", "r1.mp4", { format: "180-sbs" });
  // Same-length replacement → identical header size, nothing moves.
  const again = await writeFormat("r1.mp4", "r2.mp4", { format: "180-sbs" });
  assert.equal(again.p.strategy, "same-size");
  assert.equal(again.p.removed.v1, 1);
  assert.equal(again.p.removed.v2, 2, "st3d + sv3d");
  // Switching to a shorter format → padding (free box), still zero shift.
  const shorter = await writeFormat("r1.mp4", "r3.mp4", { format: "360-mono" });
  assert.equal(shorter.p.strategy, "padding");
  assert.equal(sideData(path("r3.mp4")).stereo, null);
  // Remove all.
  const rm = await writeFormat("r1.mp4", "r4.mp4", { format: "flat-mono" });
  assert.ok(rm.v.ok);
  assert.deepEqual(sideData(path("r4.mp4")), { spherical: null, stereo: null });
  assert.equal(rm.v.after.meta.effective, null);
  assert.equal(packetHashes(path("r4.mp4")), packetHashes(path("faststart.mp4")));
});

test("V1 XML is well-formed and parsed back exactly", async () => {
  const { v } = await writeFormat("moovend.mp4", "x1.mp4", {
    format: "180-sbs", v1: { heading: 180, crop: { cW: 2880, cH: 2880, fW: 5760, fH: 2880, cL: 1440, cT: 0 } }
  });
  const v1 = v.after.meta.v1;
  assert.ok(v1.wellFormed);
  assert.equal(v1.tags.ProjectionType, "half_equirectangular");
  assert.equal(v1.tags.StereoMode, "left-right");
  assert.equal(v1.tags.InitialViewHeadingDegrees, "180");
  assert.equal(v1.tags.FullPanoWidthPixels, "5760");
  assert.match(v1.xml, /^<\?xml version="1\.0"\?><rdf:SphericalVideo\nxmlns:rdf=/);
  // XML special characters in custom values are escaped, not injected.
  const { v: v2 } = await writeFormat("moovend.mp4", "x2.mp4", { format: "360-mono", v1: { projectionType: "a<b&c" } });
  assert.equal(v2.after.meta.v1.tags.ProjectionType, "a<b&c");
  assert.ok(v2.after.meta.v1.xml.includes("a&lt;b&amp;c"));
});

test("standards: V1-only and V2-only", async () => {
  const v1only = await writeFormat("faststart.mp4", "v1.mp4", { format: "360-tb", standard: "v1" });
  assert.ok(v1only.v.after.meta.v1);
  assert.equal(v1only.v.after.meta.v2, null);
  assert.equal(sideData(path("v1.mp4")).spherical.projection, "equirectangular");
  const v2only = await writeFormat("faststart.mp4", "v2.mp4", { format: "360-tb", standard: "v2" });
  assert.equal(v2only.v.after.meta.v1, null);
  assert.equal(v2only.v.after.meta.v2.st3d, 1);
});

test("FFmpeg's own V2 writer round-trips through our reader", async () => {
  await writeFormat("faststart.mp4", "ours.mp4", { format: "180-sbs", standard: "v2" });
  ff("-i", path("ours.mp4"), "-c", "copy", "-strict", "unofficial", path("theirs.mp4"));
  const a = await MetaFix.analyze(await blobOf("theirs.mp4"));
  assert.equal(a.meta.v2.meaning.key, "180-sbs");
  assert.equal(a.meta.v2.sv3d.bounds.left, 0.25);
});

test("stco is promoted to co64 when a shifted offset would pass 4 GB", async () => {
  const blob = await blobOf("faststart.mp4");
  const a = await MetaFix.analyze(blob);
  // Pretend the media sits just below 4 GB: rewrite the chunk offsets in the cached header.
  const { moovU8, chunkTables } = a._raw;
  const dv = new DataView(moovU8.buffer, moovU8.byteOffset, moovU8.byteLength);
  const t = chunkTables[0];
  const cs = t.start + t.hdr;
  const count = dv.getUint32(cs + 4);
  for (let i = 0; i < count; i++) dv.setUint32(cs + 8 + i * 4, 0xffffff00 + i);
  const p = MetaFix.plan(a, MetaFix.buildSpec({ format: "180-sbs" }));
  assert.ok(p.notes.some((n) => n.includes("co64")), "expected a co64 promotion note");
  const tree = MetaFix._internal.parseTree(p.splices.find((s) => s.start === a._raw.moovBox.start).bytes);
  const find = (n, type) => n.children?.flatMap((c) => (c.type === type ? [c] : find(c, type))) || [];
  const co64 = find(tree, "co64");
  assert.ok(co64.length >= 1);
  const cv = new DataView(p.splices.find((s) => s.start === a._raw.moovBox.start).bytes.buffer);
  const first = co64[0].start + co64[0].hdr;
  const v = cv.getUint32(first + 8) * 2 ** 32 + cv.getUint32(first + 12);
  assert.equal(v, 0xffffff00 + p.delta);
});

test("rejects non-MP4 input with a friendly error", async () => {
  writeFileSync(path("junk.mp4"), new Uint8Array(4096).fill(0x41));
  await assert.rejects(MetaFix.analyze(await blobOf("junk.mp4")), (e) => e instanceof MetaFix.MetaFixError);
  // Interrupted recording: mdat but no moov.
  const fs = new Uint8Array(await (await blobOf("moovend.mp4")).arrayBuffer());
  const a = await MetaFix.analyze(await blobOf("moovend.mp4"));
  writeFileSync(path("nomoov.mp4"), fs.slice(0, a._raw.moovBox.start));
  await assert.rejects(MetaFix.analyze(await blobOf("nomoov.mp4")), (e) => e.code === "NO_MOOV");
});

test("verify catches a corrupted output (media shifted by one byte)", async () => {
  const inBlob = await blobOf("faststart.mp4");
  const a = await MetaFix.analyze(inBlob);
  const p = MetaFix.plan(a, MetaFix.buildSpec({ format: "360-mono" }));
  const good = MetaFix.buildBlob(inBlob, p);
  const cut = p.splices[p.splices.length - 1].start + p.splices[p.splices.length - 1].bytes.length;
  const bad = new Blob([good.slice(0, cut), Uint8Array.of(0), good.slice(cut)]);
  const v = await MetaFix.verify(inBlob, bad, a, p);
  assert.equal(v.ok, false);
  assert.equal(v.checks.find((c) => c.id === "media").ok, false);
  assert.equal(v.checks.find((c) => c.id === "size").ok, false);
});
